name: Deploy
on: [push]
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      OWNER: rendau
      REPO: gl2sl
      IMAGE: gl2sl
      DOCKERHUB_USER: rendau
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Docker login
        env:
          DOCKERHUB_PSW: ${{ secrets.DOCKERHUB_PSW }}
        run: |
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PSW

      - name: Docker build
        run: |
          docker build -t $DOCKERHUB_USER/$IMAGE:latest .

      - name: Docker push
        run: |
          docker push $DOCKERHUB_USER/$IMAGE:latest
